// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow that analyzes a photo and generates relevant keywords or themes.
 *
 * - analyzePhotoForKeywords - A function that handles the photo analysis process.
 * - AnalyzePhotoForKeywordsInput - The input type for the analyzePhotoForKeywords function.
 * - AnalyzePhotoForKeywordsOutput - The return type for the analyzePhotoForKeywords function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzePhotoForKeywordsInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzePhotoForKeywordsInput = z.infer<typeof AnalyzePhotoForKeywordsInputSchema>;

const AnalyzePhotoForKeywordsOutputSchema = z.object({
  keywords: z.array(z.string()).describe('An array of keywords or themes relevant to the photo.'),
});
export type AnalyzePhotoForKeywordsOutput = z.infer<typeof AnalyzePhotoForKeywordsOutputSchema>;

export async function analyzePhotoForKeywords(input: AnalyzePhotoForKeywordsInput): Promise<AnalyzePhotoForKeywordsOutput> {
  return analyzePhotoForKeywordsFlow(input);
}

const analyzePhotoForKeywordsPrompt = ai.definePrompt({
  name: 'analyzePhotoForKeywordsPrompt',
  input: {schema: AnalyzePhotoForKeywordsInputSchema},
  output: {schema: AnalyzePhotoForKeywordsOutputSchema},
  prompt: `You are an AI that analyzes photos and generates relevant keywords or themes.

  Analyze the photo and generate an array of keywords or themes that are relevant to the photo.  Return the keywords as a JSON array of strings.

  Photo: {{media url=photoDataUri}}`,
});

const analyzePhotoForKeywordsFlow = ai.defineFlow(
  {
    name: 'analyzePhotoForKeywordsFlow',
    inputSchema: AnalyzePhotoForKeywordsInputSchema,
    outputSchema: AnalyzePhotoForKeywordsOutputSchema,
  },
  async input => {
    const {output} = await analyzePhotoForKeywordsPrompt(input);
    return output!;
  }
);
